[workspace]
members = ["packet-binser-derive"]

[package]
name = "packet-binser"
version = "0.1.0"
edition = "2021"

[features]
default = []
derive = ["packet-binser-derive"]

[dependencies]
lbytes = "0.1.1"
paste = "1.0.15"
residua-zigzag = "0.1.0"
packet-binser-derive = { path = "./packet-binser-derive", optional = true }
